### ISSUE TITLE
Create library to control the L298N motor controller

### ISSUE THREAD

**Issue by stantonious** [cyxl/Seeed_Grove_Vision_AI_Module_V2#3]
Use this library as a guide https://github.com/cyxl/Seeed_Grove_Vision_AI_Module_V2/blob/main/EPII_CM55M_APP_S/app/scenario_app/pilboi-freertos/uln2003.h
Read
https://howtomechatronics.com/tutorials/arduino/arduino-dc-motor-control-tutorial-l298n-pwm-h-bridge/

You'll need to

- Create an init() to initialize the GPIOs (4 in total to control 2 dc motors)
- Create functions to start/stop either motor `start(uint16_t motorid)` and `stop(uint16_t motorid)`
To Test
- Wire up 2 motors to the L298N and ensure you can turn them on/off independently

**Comment by cyxl** [comment]
Done
